### ISSUE TITLE
Error in line 40

### ISSUE THREAD

**Issue by amitaknkpt** [UltimateHackers/Zoom#1]
C:\Users\WIZARDS\Zoom>zoom.py -u http://victimsite.com/
[1;33m  ____
 /_  / ___  ___  ____
  / /_/ [97m_ \/ _[1;33m \/    \
 /___/\___[97m/\[1;33m___/_/_/_/[1;m

 [1;33m+--------------------------+-------------------------------+[1;m
 [1;33m| Display Name             | Username                      |[1;m
 [1;33m+--------------------------+-------------------------------+[1;m
Traceback (most recent call last):
  File "C:\Users\WIZARDS\Zoom\zoom.py", line 40, in <module>
    print (' %s|%s %-25s%s|%s %-30s%s|%s' % (yellow, end, key['name'], yellow, end, key['slug'], yellow, end))
TypeError: string indices must be integers

C:\Users\WIZARDS\Zoom>

**Comment by UltimateHackers** [comment]
Fixed.
